### ISSUE TITLE
Installation failure, I am not even sure what caused it

### ISSUE THREAD

**Issue by takase1121** [termux/termux-tasker#28]
Had both termux (FDroid) and other plugins installed, only Tasker won't install. Checked the logs, I am not even sure how to explain this. I need help.

```
12-24 01:44:00.576  1472  1549 E SELinux : SELinux:  setxattr failed: /data/app/com.termux.tasker-wmP69HJO5FGf_f0bLMbQvQ==:  Operation not permitted
12-24 01:44:00.576  1472  1549 E SELinux : SELinux:  setxattr failed: /data/app/com.termux.tasker-wmP69HJO5FGf_f0bLMbQvQ==/lib:  Operation not permitted
12-24 01:44:00.578  1472  1549 E PackageManager: Adding duplicate user id: 10163 name=com.termux.tasker
12-24 01:44:00.606  1472  1549 E Installer: Calling thread PackageManager is holding 0xce0ae85
12-24 01:44:00.606  1472  1549 E Installer: java.lang.Throwable
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.Installer.checkBeforeRemote(Installer.java:156)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.Installer.destroyAppData(Installer.java:209)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppDataLeafLIF(PackageManagerService.java:9971)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppDataLIF(PackageManagerService.java:9956)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10488)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10255)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:16892)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18135)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17606)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.access$3300(PackageManagerService.java:407)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15436)
12-24 01:44:00.606  1472  1549 E Installer:     at android.os.Handler.handleCallback(Handler.java:873)
12-24 01:44:00.606  1472  1549 E Installer:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 01:44:00.606  1472  1549 E Installer:     at android.os.Looper.loop(Looper.java:201)
12-24 01:44:00.606  1472  1549 E Installer:     at android.os.HandlerThread.run(HandlerThread.java:65)
12-24 01:44:00.606  1472  1549 E Installer:     at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-24 01:44:00.608   680  1650 E         : Couldn't opendir /data/data/com.termux.tasker: No such file or directory
12-24 01:44:00.608   680  1650 E installd: Failed to delete /data/data/com.termux.tasker: No such file or directory
12-24 01:44:00.608   680  1650 E         : Couldn't opendir /data/user_de/0/com.termux.tasker: No such file or directory
12-24 01:44:00.608   680  1650 E installd: Failed to delete /data/user_de/0/com.termux.tasker: No such file or directory
12-24 01:44:00.634  1472  1549 W PackageManager: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to delete /data/user_de/0/com.termux.tasker (code 2)
12-24 01:44:00.635  1472  1549 E Installer: Calling thread PackageManager is holding 0xce0ae85
12-24 01:44:00.635  1472  1549 E Installer: java.lang.Throwable
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.Installer.checkBeforeRemote(Installer.java:156)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.Installer.destroyAppProfiles(Installer.java:387)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppProfilesLeafLIF(PackageManagerService.java:9994)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppProfilesLIF(PackageManagerService.java:9985)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10490)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10255)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:16892)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18135)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17606)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService.access$3300(PackageManagerService.java:407)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15436)
12-24 01:44:00.635  1472  1549 E Installer:     at android.os.Handler.handleCallback(Handler.java:873)
12-24 01:44:00.635  1472  1549 E Installer:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 01:44:00.635  1472  1549 E Installer:     at android.os.Looper.loop(Looper.java:201)
12-24 01:44:00.635  1472  1549 E Installer:     at android.os.HandlerThread.run(HandlerThread.java:65)
12-24 01:44:00.635  1472  1549 E Installer:     at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-24 01:44:00.637  1472  1549 W PackageManager: Package couldn't be installed in /data/app/com.termux.tasker-wmP69HJO5FGf_f0bLMbQvQ==
12-24 01:44:00.637  1472  1549 W PackageManager: com.android.server.pm.PackageManagerException: Package com.termux.tasker has no signatures that match those in shared user com.termux; ignoring!
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerServiceUtils.verifySignatures(PackageManagerServiceUtils.java:629)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.commitScanResultsLocked(PackageManagerService.java:10596)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10482)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10255)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:16892)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18135)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17606)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService.access$3300(PackageManagerService.java:407)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15436)
12-24 01:44:00.637  1472  1549 W PackageManager:        at android.os.Handler.handleCallback(Handler.java:873)
12-24 01:44:00.637  1472  1549 W PackageManager:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 01:44:00.637  1472  1549 W PackageManager:        at android.os.Looper.loop(Looper.java:201)
12-24 01:44:00.637  1472  1549 W PackageManager:        at android.os.HandlerThread.run(HandlerThread.java:65)
12-24 01:44:00.637  1472  1549 W PackageManager:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-24 01:44:00.640   680  1650 E cutils  : Failed to open(/data/misc/profiles/cur/0/com.termux.tasker/primary.prof): No such file or directory
12-24 01:44:00.640   680  1650 E installed: Failed to prepare /data/misc/profiles/cur/0/com.termux.tasker/primary.prof: No such file or directory
12-24 01:44:00.641  1472  1549 E ArtManagerService: Failed to prepare profile for com.termux.tasker:/data/app/com.termux.tasker-wmP69HJO5FGf_f0bLMbQvQ==/base.apk
12-24 01:44:00.646  1472  1549 I InstallationStatistic: com.termux.tasker|com.google.android.packageinstaller|1794|170|197|94|1057|0
```

**Comment by xeffyr** [comment]
Are you sure that you are installing everything from **same** source (e.g F-Droid) ?

Line
>12-24 01:44:00.637  1472  1549 W PackageManager: com.android.server.pm.PackageManagerException: Package com.termux.tasker has no signatures that match those in shared user com.termux; ignoring!

shows that no.

**Comment by takase1121** [comment]
That installation log is for the debug APK from the README file. Even if I install it from F-Droid its the same. The signature problem just won't go away.

```
12-24 11:03:18.565  1428  1510 E SELinux : SELinux:  setxattr failed: /data/app/com.termux.tasker-hOk9QlqC9dxwaxGFIsDBjA==:  Operation not permitted
12-24 11:03:18.565  1428  1510 E SELinux : SELinux:  setxattr failed: /data/app/com.termux.tasker-hOk9QlqC9dxwaxGFIsDBjA==/lib:  Operation not permitted
12-24 11:03:18.567  1428  1510 E PackageManager: Adding duplicate user id: 10163 name=com.termux.tasker
12-24 11:03:18.571  1428  1510 E Installer: Calling thread PackageManager is holding 0xfbec37f
12-24 11:03:18.571  1428  1510 E Installer: java.lang.Throwable
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.Installer.checkBeforeRemote(Installer.java:156)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.Installer.destroyAppData(Installer.java:209)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppDataLeafLIF(PackageManagerService.java:9971)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppDataLIF(PackageManagerService.java:9956)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10488)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10255)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:16892)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18135)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17606)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.access$3300(PackageManagerService.java:407)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15436)
12-24 11:03:18.571  1428  1510 E Installer:     at android.os.Handler.handleCallback(Handler.java:873)
12-24 11:03:18.571  1428  1510 E Installer:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 11:03:18.571  1428  1510 E Installer:     at android.os.Looper.loop(Looper.java:201)
12-24 11:03:18.571  1428  1510 E Installer:     at android.os.HandlerThread.run(HandlerThread.java:65)
12-24 11:03:18.571  1428  1510 E Installer:     at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-24 11:03:18.573   691  1701 E         : Couldn't opendir /data/data/com.termux.tasker: No such file or directory
12-24 11:03:18.573   691  1701 E installd: Failed to delete /data/data/com.termux.tasker: No such file or directory
12-24 11:03:18.573   691  1701 E         : Couldn't opendir /data/user_de/0/com.termux.tasker: No such file or directory
12-24 11:03:18.573   691  1701 E installd: Failed to delete /data/user_de/0/com.termux.tasker: No such file or directory
12-24 11:03:18.587  1428  1510 W PackageManager: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to delete /data/user_de/0/com.termux.tasker (code 2)
12-24 11:03:18.587  1428  1510 E Installer: Calling thread PackageManager is holding 0xfbec37f
12-24 11:03:18.587  1428  1510 E Installer: java.lang.Throwable
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.Installer.checkBeforeRemote(Installer.java:156)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.Installer.destroyAppProfiles(Installer.java:387)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppProfilesLeafLIF(PackageManagerService.java:9994)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.destroyAppProfilesLIF(PackageManagerService.java:9985)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10490)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10255)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:16892)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18135)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17606)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService.access$3300(PackageManagerService.java:407)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15436)
12-24 11:03:18.587  1428  1510 E Installer:     at android.os.Handler.handleCallback(Handler.java:873)
12-24 11:03:18.587  1428  1510 E Installer:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 11:03:18.587  1428  1510 E Installer:     at android.os.Looper.loop(Looper.java:201)
12-24 11:03:18.587  1428  1510 E Installer:     at android.os.HandlerThread.run(HandlerThread.java:65)
12-24 11:03:18.587  1428  1510 E Installer:     at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-24 11:03:18.612  1428  1510 W PackageManager: Package couldn't be installed in /data/app/com.termux.tasker-hOk9QlqC9dxwaxGFIsDBjA==
12-24 11:03:18.612  1428  1510 W PackageManager: com.android.server.pm.PackageManagerException: Package com.termux.tasker has no signatures that match those in shared user com.termux; ignoring!
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerServiceUtils.verifySignatures(PackageManagerServiceUtils.java:629)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.commitScanResultsLocked(PackageManagerService.java:10596)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10482)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10255)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:16892)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18135)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:17606)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService.access$3300(PackageManagerService.java:407)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15436)
12-24 11:03:18.612  1428  1510 W PackageManager:        at android.os.Handler.handleCallback(Handler.java:873)
12-24 11:03:18.612  1428  1510 W PackageManager:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 11:03:18.612  1428  1510 W PackageManager:        at android.os.Looper.loop(Looper.java:201)
12-24 11:03:18.612  1428  1510 W PackageManager:        at android.os.HandlerThread.run(HandlerThread.java:65)
12-24 11:03:18.612  1428  1510 W PackageManager:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-24 11:03:18.613   691  1701 E cutils  : Failed to open(/data/misc/profiles/cur/0/com.termux.tasker/primary.prof): No such file or directory
12-24 11:03:18.613   691  1701 E installed: Failed to prepare /data/misc/profiles/cur/0/com.termux.tasker/primary.prof: No such file or directory
12-24 11:03:18.613  1428  1510 E ArtManagerService: Failed to prepare profile for com.termux.tasker:/data/app/com.termux.tasker-hOk9QlqC9dxwaxGFIsDBjA==/base.apk
12-24 11:03:18.618  1428  1510 I InstallationStatistic: com.termux.tasker|com.google.android.packageinstaller|2768|172|196|374|1556|0
``` 
this is when I install it from F-Droid.

**Comment by xeffyr** [comment]
> That installation log is for the debug APK from the README file.

Why you are mixing installations from various sources ? Each source (git, fdroid, google play) is incompatible with each other.

Debug apk will obviously fail with Termux app and other add-ons from F-Droid or Google Play and same goes for all other source combinations.

> Even if I install it from F-Droid its the same.

I just installed everything from F-Droid without errors. Make sure that tasker addon has the next sha-256:
```
097b4c7b47d86e07159b2de816189bb0b2019ff44c5baa4d052cc49dec3a19c6
```

Also, APKs from F-Droid (gzipped for uploading to Github):
[com.termux.api_38.apk.gz](https://github.com/termux/termux-tasker/files/3998175/com.termux.api_38.apk.gz)
[com.termux.boot_7.apk.gz](https://github.com/termux/termux-tasker/files/3998176/com.termux.boot_7.apk.gz)
[com.termux.styling_25.apk.gz](https://github.com/termux/termux-tasker/files/3998177/com.termux.styling_25.apk.gz)
[com.termux.tasker_3.apk.gz](https://github.com/termux/termux-tasker/files/3998178/com.termux.tasker_3.apk.gz)
[com.termux.widget_11.apk.gz](https://github.com/termux/termux-tasker/files/3998179/com.termux.widget_11.apk.gz)
[com.termux.window_13.apk.gz](https://github.com/termux/termux-tasker/files/3998180/com.termux.window_13.apk.gz)

\- if **full reinstallation** (termux and all add-ons) fail with these, seek problem with your device.

**Comment by romansh-dev** [comment]
Thanks, that usefull topic
